version: '3.3'

services:

  gateway:
    image: nginx:1.19.6
    restart: unless-stopped
    container_name: gateway
    network_mode: host
    env_file:
      - port_host.env
    volumes:
      - ./static:/var/www/static
      - ./reload.sh:/etc/nginx/reload.sh
      - ./gateway.nginx:/etc/nginx/conf.d/conf.nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./start-nginx.sh:/etc/nginx/start-nginx.sh
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    environment:
      CHOKIDAR_USEPOLLING: true
    command: /bin/bash -c  "chmod +x /etc/nginx/*.sh && /etc/nginx/start-nginx.sh"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: 256m

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: 256m
