version: '3.3'

services:

  mongodb:
    image: mongo:6.0.8
    restart: unless-stopped
    env_file:
      - ../../config/prod_mongo.env
    volumes:
      - ../mongodb/data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - "1201:27017"
    logging:
      driver: "json-file"
      options:
        tag: "slink-mongodb"
        max-size: 256m

  redis:
    image: redis:7.0.12-alpine3.18
    restart: unless-stopped
    env_file:
      - ../../config/prod_redis.env
    volumes:
      - ../redis/data:/data
    ports:
      - "1104:6379"
    logging:
      driver: "json-file"
      options:
        tag: "slink_redis"
        max-size: 256m

  entityservice:
    image: amazoncorretto:17.0.6-alpine
    depends_on:
      - mongodb
      - redis
    env_file:
      - ../../config/prod_mongo_auth.env
      - ../../config/prod_redis_auth.env
    restart: unless-stopped
    volumes:
      - ./java/entity-api-0.0.1-SNAPSHOT.jar:/gjava/java.jar
      - ../files:/gjava/files
      - ./GeoLite2:/gjava/GeoLite2
    environment:
      appMode: prod
      baseHost: https://slink.sbs
      spring_data_mongodb_host: mongodb
      geoLiteCountryDataBase: //gjava//GeoLite2//GeoLite2-Country//GeoLite2-Country.mmdb
      geoLiteCityDataBase: //gjava//GeoLite2//GeoLite2-City//GeoLite2-City.mmdb
    command: /bin/sh -c "cd /gjava && chmod +x /gjava/*.jar && java -jar /gjava/java.jar"
    ports:
      - "127.0.0.1:1103:8667"
    logging:
      driver: "json-file"
      options:
        tag: "slink-entry-service"
        max-size: 256m

  frontapiservice:
    image: amazoncorretto:17.0.6-alpine
    depends_on:
      - mongodb
      - redis
    env_file:
      - ../../config/prod_mongo_auth.env
      - ../../config/prod_redis_auth.env
    restart: unless-stopped
    volumes:
       - ./java/front-api-0.0.1-SNAPSHOT.jar:/gjava/java.jar
       - ../files:/gjava/files
       - ./GeoLite2:/gjava/GeoLite2
    environment:
      appMode: prod
      baseHost: https://slink.sbs
      spring_data_mongodb_host: mongodb
      geoLiteCountryDataBase: //gjava//GeoLite2//GeoLite2-Country//GeoLite2-Country.mmdb
      geoLiteCityDataBase: //gjava//GeoLite2//GeoLite2-City//GeoLite2-City.mmdb
    command: /bin/sh -c "cd /gjava && chmod +x /gjava/*.jar && java -jar /gjava/java.jar"
    ports:
      - "1102:8666"
    logging:
      driver: "json-file"
      options:
        tag: "slink-api-service"
        max-size: 256m

  schedulerservice:
    image: amazoncorretto:17.0.6-alpine
    depends_on:
      - mongodb
      - redis
    env_file:
      - ../../config/prod_mongo_auth.env
      - ../../config/prod_redis_auth.env
    restart: unless-stopped
    volumes:
      - ./java/scheduler-0.0.1-SNAPSHOT.jar:/gjava/java.jar
      - ../files:/gjava/files
      - ./GeoLite2:/gjava/GeoLite2
    environment:
      appMode: prod
      baseHost: https://slink.sbs
      spring_data_mongodb_host: mongodb
      geoLiteCountryDataBase: //gjava//GeoLite2//GeoLite2-Country//GeoLite2-Country.mmdb
      geoLiteCityDataBase: //gjava//GeoLite2//GeoLite2-City//GeoLite2-City.mmdb
    command: /bin/sh -c "cd /gjava && chmod +x /gjava/*.jar && java -jar /gjava/java.jar"
    logging:
      driver: "json-file"
      options:
        tag: "slink-scheduler-service"
        max-size: 256m

  frontservice:
    image: nginx:1.23.3-alpine
    depends_on:
      - frontapiservice
    restart: unless-stopped
    volumes:
      - ./front:/usr/share/nginx/html
      - ../files:/usr/share/nginx/html/files
      - ./gateway/nginx.front.conf:/etc/nginx/nginx.conf
    environment:
      REACT_APP_APP_URL: https://slink.sbs
    ports:
      - "127.0.0.1:1101:80"
    logging:
      driver: "json-file"
      options:
        tag: "slink-front-service"
        max-size: 256m
